Performance meeting updates
JasonGross/slow-coq-examples pull request #3
Opened 2016-11-09 17:03 UTC by psteckler

Added assessments for each open example based on discussions with INRIA (Maxime, Matthieu, PMP). Also distinguished partially-fixed from fixed examples.

2016-11-09 17:10 UTC, JasonGross requested changes
Thanks!  If you make the changes I requested, I'll merge.

2016-11-09 17:10 UTC, JasonGross commented on README.md
> +  `cbv [some identifiers]` can run through 64 GB of RAM in 15 minutes
Please add a reference to ```[`slow_fiat_examples/README.md`](./slow_fiat_examples/README.md) for
    more details and instructions on running.```, as was in the original mention

2016-11-09 17:10 UTC, JasonGross commented on README.md
>    [bug #4779](https://coq.inria.fr/bugs/show_bug.cgi?id=4779) in the next
Please update this to mention that 4779 has been moved down

2016-11-09 17:10 UTC, JasonGross commented on README.md
> +  `pose y as x; change y with x in H` can be 1300x slower than `set (x := y) in H`
Please add a reference to ```[`slow_fiat_examples/README.md`](./slow_fiat_examples/README.md) for
    more details and instructions on running.```, as was in the original mention

2016-11-09 19:26 UTC, psteckler commented on README.md
> +  `pose y as x; change y with x in H` can be 1300x slower than `set (x := y) in H`
The changes you suggested should be done, please check them.

2016-11-11 02:26 UTC, JasonGross approved these changes
Thanks!

2016-11-11 02:26 UTC, merged